//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentResultStatus) DeepCopyInto(out *AgentResultStatus) {
	*out = *in
	if in.ExitCode != nil {
		in, out := &in.ExitCode, &out.ExitCode
		*out = new(int32)
		**out = **in
	}
	if in.ReportedAt != nil {
		in, out := &in.ReportedAt, &out.ReportedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentResultStatus.
func (in *AgentResultStatus) DeepCopy() *AgentResultStatus {
	if in == nil {
		return nil
	}
	out := new(AgentResultStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSpec) DeepCopyInto(out *AgentSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(ModelSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSpec.
func (in *AgentSpec) DeepCopy() *AgentSpec {
	if in == nil {
		return nil
	}
	out := new(AgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArchiveStatus) DeepCopyInto(out *ArchiveStatus) {
	*out = *in
	if in.FinishedAt != nil {
		in, out := &in.FinishedAt, &out.FinishedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArchiveStatus.
func (in *ArchiveStatus) DeepCopy() *ArchiveStatus {
	if in == nil {
		return nil
	}
	out := new(ArchiveStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendSpec) DeepCopyInto(out *BackendSpec) {
	*out = *in
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(S3Backend)
		(*in).DeepCopyInto(*out)
	}
	if in.PVC != nil {
		in, out := &in.PVC, &out.PVC
		*out = new(PVCBackend)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendSpec.
func (in *BackendSpec) DeepCopy() *BackendSpec {
	if in == nil {
		return nil
	}
	out := new(BackendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClassRef) DeepCopyInto(out *ClassRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClassRef.
func (in *ClassRef) DeepCopy() *ClassRef {
	if in == nil {
		return nil
	}
	out := new(ClassRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependaProxyService) DeepCopyInto(out *DependaProxyService) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependaProxyService.
func (in *DependaProxyService) DeepCopy() *DependaProxyService {
	if in == nil {
		return nil
	}
	out := new(DependaProxyService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EgressPeer) DeepCopyInto(out *EgressPeer) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(PeerSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]NetworkPolicyPort, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EgressPeer.
func (in *EgressPeer) DeepCopy() *EgressPeer {
	if in == nil {
		return nil
	}
	out := new(EgressPeer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EngineSpec) DeepCopyInto(out *EngineSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EngineSpec.
func (in *EngineSpec) DeepCopy() *EngineSpec {
	if in == nil {
		return nil
	}
	out := new(EngineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitProxyService) DeepCopyInto(out *GitProxyService) {
	*out = *in
	out.TokenSecretRef = in.TokenSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitProxyService.
func (in *GitProxyService) DeepCopy() *GitProxyService {
	if in == nil {
		return nil
	}
	out := new(GitProxyService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitStateStatus) DeepCopyInto(out *GitStateStatus) {
	*out = *in
	if in.PullRequest != nil {
		in, out := &in.PullRequest, &out.PullRequest
		*out = new(PullRequestRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitStateStatus.
func (in *GitStateStatus) DeepCopy() *GitStateStatus {
	if in == nil {
		return nil
	}
	out := new(GitStateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IssueRef) DeepCopyInto(out *IssueRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IssueRef.
func (in *IssueRef) DeepCopy() *IssueRef {
	if in == nil {
		return nil
	}
	out := new(IssueRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelSpec) DeepCopyInto(out *ModelSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelSpec.
func (in *ModelSpec) DeepCopy() *ModelSpec {
	if in == nil {
		return nil
	}
	out := new(ModelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPolicyPort) DeepCopyInto(out *NetworkPolicyPort) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPolicyPort.
func (in *NetworkPolicyPort) DeepCopy() *NetworkPolicyPort {
	if in == nil {
		return nil
	}
	out := new(NetworkPolicyPort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkSpec) DeepCopyInto(out *NetworkSpec) {
	*out = *in
	if in.ExtraEgress != nil {
		in, out := &in.ExtraEgress, &out.ExtraEgress
		*out = make([]EgressPeer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkSpec.
func (in *NetworkSpec) DeepCopy() *NetworkSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OllamaService) DeepCopyInto(out *OllamaService) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OllamaService.
func (in *OllamaService) DeepCopy() *OllamaService {
	if in == nil {
		return nil
	}
	out := new(OllamaService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PVCBackend) DeepCopyInto(out *PVCBackend) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PVCBackend.
func (in *PVCBackend) DeepCopy() *PVCBackend {
	if in == nil {
		return nil
	}
	out := new(PVCBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeerSelector) DeepCopyInto(out *PeerSelector) {
	*out = *in
	if in.PodSelector != nil {
		in, out := &in.PodSelector, &out.PodSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeerSelector.
func (in *PeerSelector) DeepCopy() *PeerSelector {
	if in == nil {
		return nil
	}
	out := new(PeerSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PhaseTransition) DeepCopyInto(out *PhaseTransition) {
	*out = *in
	in.At.DeepCopyInto(&out.At)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PhaseTransition.
func (in *PhaseTransition) DeepCopy() *PhaseTransition {
	if in == nil {
		return nil
	}
	out := new(PhaseTransition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProbeAttemptStatus) DeepCopyInto(out *ProbeAttemptStatus) {
	*out = *in
	if in.LastAttemptAt != nil {
		in, out := &in.LastAttemptAt, &out.LastAttemptAt
		*out = (*in).DeepCopy()
	}
	if in.NextEligibleAt != nil {
		in, out := &in.NextEligibleAt, &out.NextEligibleAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProbeAttemptStatus.
func (in *ProbeAttemptStatus) DeepCopy() *ProbeAttemptStatus {
	if in == nil {
		return nil
	}
	out := new(ProbeAttemptStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PullRequestRef) DeepCopyInto(out *PullRequestRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PullRequestRef.
func (in *PullRequestRef) DeepCopy() *PullRequestRef {
	if in == nil {
		return nil
	}
	out := new(PullRequestRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreAttemptStatus) DeepCopyInto(out *RestoreAttemptStatus) {
	*out = *in
	if in.Roots != nil {
		in, out := &in.Roots, &out.Roots
		*out = make([]RestoredRootStatus, len(*in))
		copy(*out, *in)
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreAttemptStatus.
func (in *RestoreAttemptStatus) DeepCopy() *RestoreAttemptStatus {
	if in == nil {
		return nil
	}
	out := new(RestoreAttemptStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoredRootStatus) DeepCopyInto(out *RestoredRootStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoredRootStatus.
func (in *RestoredRootStatus) DeepCopy() *RestoredRootStatus {
	if in == nil {
		return nil
	}
	out := new(RestoredRootStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Backend) DeepCopyInto(out *S3Backend) {
	*out = *in
	out.CredentialsSecretRef = in.CredentialsSecretRef
	if in.ForcePathStyle != nil {
		in, out := &in.ForcePathStyle, &out.ForcePathStyle
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Backend.
func (in *S3Backend) DeepCopy() *S3Backend {
	if in == nil {
		return nil
	}
	out := new(S3Backend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxClass) DeepCopyInto(out *SandboxClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxClass.
func (in *SandboxClass) DeepCopy() *SandboxClass {
	if in == nil {
		return nil
	}
	out := new(SandboxClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SandboxClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxClassList) DeepCopyInto(out *SandboxClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SandboxClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxClassList.
func (in *SandboxClassList) DeepCopy() *SandboxClassList {
	if in == nil {
		return nil
	}
	out := new(SandboxClassList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SandboxClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxClassSpec) DeepCopyInto(out *SandboxClassSpec) {
	*out = *in
	in.Agent.DeepCopyInto(&out.Agent)
	out.Engine = in.Engine
	in.Services.DeepCopyInto(&out.Services)
	in.Storage.DeepCopyInto(&out.Storage)
	in.Network.DeepCopyInto(&out.Network)
	out.Timeouts = in.Timeouts
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxClassSpec.
func (in *SandboxClassSpec) DeepCopy() *SandboxClassSpec {
	if in == nil {
		return nil
	}
	out := new(SandboxClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxClassStatus) DeepCopyInto(out *SandboxClassStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxClassStatus.
func (in *SandboxClassStatus) DeepCopy() *SandboxClassStatus {
	if in == nil {
		return nil
	}
	out := new(SandboxClassStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxEnvironment) DeepCopyInto(out *SandboxEnvironment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxEnvironment.
func (in *SandboxEnvironment) DeepCopy() *SandboxEnvironment {
	if in == nil {
		return nil
	}
	out := new(SandboxEnvironment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SandboxEnvironment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxEnvironmentList) DeepCopyInto(out *SandboxEnvironmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SandboxEnvironment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxEnvironmentList.
func (in *SandboxEnvironmentList) DeepCopy() *SandboxEnvironmentList {
	if in == nil {
		return nil
	}
	out := new(SandboxEnvironmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SandboxEnvironmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxEnvironmentSpec) DeepCopyInto(out *SandboxEnvironmentSpec) {
	*out = *in
	out.ClassRef = in.ClassRef
	in.Task.DeepCopyInto(&out.Task)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxEnvironmentSpec.
func (in *SandboxEnvironmentSpec) DeepCopy() *SandboxEnvironmentSpec {
	if in == nil {
		return nil
	}
	out := new(SandboxEnvironmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxEnvironmentStatus) DeepCopyInto(out *SandboxEnvironmentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Slot.DeepCopyInto(&out.Slot)
	if in.WaitFor != nil {
		in, out := &in.WaitFor, &out.WaitFor
		*out = new(WaitForStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.ProbeAttempt != nil {
		in, out := &in.ProbeAttempt, &out.ProbeAttempt
		*out = new(ProbeAttemptStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.AgentResult != nil {
		in, out := &in.AgentResult, &out.AgentResult
		*out = new(AgentResultStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Snapshot != nil {
		in, out := &in.Snapshot, &out.Snapshot
		*out = new(SnapshotStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.SnapshotAttempt != nil {
		in, out := &in.SnapshotAttempt, &out.SnapshotAttempt
		*out = new(SnapshotAttemptStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.RestoreAttempt != nil {
		in, out := &in.RestoreAttempt, &out.RestoreAttempt
		*out = new(RestoreAttemptStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.QueuedSince != nil {
		in, out := &in.QueuedSince, &out.QueuedSince
		*out = (*in).DeepCopy()
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.FinishedAt != nil {
		in, out := &in.FinishedAt, &out.FinishedAt
		*out = (*in).DeepCopy()
	}
	if in.Archive != nil {
		in, out := &in.Archive, &out.Archive
		*out = new(ArchiveStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.PhaseHistory != nil {
		in, out := &in.PhaseHistory, &out.PhaseHistory
		*out = make([]PhaseTransition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GitState != nil {
		in, out := &in.GitState, &out.GitState
		*out = new(GitStateStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxEnvironmentStatus.
func (in *SandboxEnvironmentStatus) DeepCopy() *SandboxEnvironmentStatus {
	if in == nil {
		return nil
	}
	out := new(SandboxEnvironmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServicesSpec) DeepCopyInto(out *ServicesSpec) {
	*out = *in
	if in.GitProxy != nil {
		in, out := &in.GitProxy, &out.GitProxy
		*out = new(GitProxyService)
		**out = **in
	}
	if in.DependaProxy != nil {
		in, out := &in.DependaProxy, &out.DependaProxy
		*out = new(DependaProxyService)
		**out = **in
	}
	if in.Ollama != nil {
		in, out := &in.Ollama, &out.Ollama
		*out = new(OllamaService)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServicesSpec.
func (in *ServicesSpec) DeepCopy() *ServicesSpec {
	if in == nil {
		return nil
	}
	out := new(ServicesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlotStatus) DeepCopyInto(out *SlotStatus) {
	*out = *in
	if in.GrantedAt != nil {
		in, out := &in.GrantedAt, &out.GrantedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlotStatus.
func (in *SlotStatus) DeepCopy() *SlotStatus {
	if in == nil {
		return nil
	}
	out := new(SlotStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotAttemptStatus) DeepCopyInto(out *SnapshotAttemptStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotAttemptStatus.
func (in *SnapshotAttemptStatus) DeepCopy() *SnapshotAttemptStatus {
	if in == nil {
		return nil
	}
	out := new(SnapshotAttemptStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotStatus) DeepCopyInto(out *SnapshotStatus) {
	*out = *in
	if in.TakenAt != nil {
		in, out := &in.TakenAt, &out.TakenAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotStatus.
func (in *SnapshotStatus) DeepCopy() *SnapshotStatus {
	if in == nil {
		return nil
	}
	out := new(SnapshotStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
	in.Workspace.DeepCopyInto(&out.Workspace)
	in.Backend.DeepCopyInto(&out.Backend)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageSpec.
func (in *StorageSpec) DeepCopy() *StorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskSpec) DeepCopyInto(out *TaskSpec) {
	*out = *in
	if in.IssueRef != nil {
		in, out := &in.IssueRef, &out.IssueRef
		*out = new(IssueRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskSpec.
func (in *TaskSpec) DeepCopy() *TaskSpec {
	if in == nil {
		return nil
	}
	out := new(TaskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeoutsSpec) DeepCopyInto(out *TimeoutsSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeoutsSpec.
func (in *TimeoutsSpec) DeepCopy() *TimeoutsSpec {
	if in == nil {
		return nil
	}
	out := new(TimeoutsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WaitForStatus) DeepCopyInto(out *WaitForStatus) {
	*out = *in
	if in.DeclaredAt != nil {
		in, out := &in.DeclaredAt, &out.DeclaredAt
		*out = (*in).DeepCopy()
	}
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WaitForStatus.
func (in *WaitForStatus) DeepCopy() *WaitForStatus {
	if in == nil {
		return nil
	}
	out := new(WaitForStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceSpec) DeepCopyInto(out *WorkspaceSpec) {
	*out = *in
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceSpec.
func (in *WorkspaceSpec) DeepCopy() *WorkspaceSpec {
	if in == nil {
		return nil
	}
	out := new(WorkspaceSpec)
	in.DeepCopyInto(out)
	return out
}
